In [19]:
from PIL import Image
import numpy as np
from skimage import io
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from PIL import Image

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import os
from __future__ import print_function, division
import os
from PIL import Image
import torch
import torch.utils.data

from skimage import io

import numpy as np
# 打开图像文件
image_path = "tinySet/img/000000_10 copy.png" # 替换为你的图片文件路径
image_path2 = "tinySet/mask/000000_10 copy.png"



In [24]:
img = io.imread(image_path)
img2= io.imread(image_path2)
print(img.shape)#0-255
print(np.min(img))
print(np.max(img))
print(img2.shape)
print(np.min(img2))
print(np.max(img2))
print(img2.dtype)
unique_values, counts = np.unique(img2, return_counts=True)
print(len(counts))

(375, 1242, 3)
0
255
(375, 1242)
4
28
uint8
14


In [12]:
plt.imsave("tinySet/trail.png", img2, cmap='gray')

In [13]:
img3= io.imread("tinySet/trail.png")
print(img3)

[[[181 181 181 255]
  [181 181 181 255]
  [181 181 181 255]
  ...
  [ 73  73  73 255]
  [ 73  73  73 255]
  [ 73  73  73 255]]

 [[181 181 181 255]
  [181 181 181 255]
  [181 181 181 255]
  ...
  [ 73  73  73 255]
  [ 73  73  73 255]
  [ 73  73  73 255]]

 [[181 181 181 255]
  [181 181 181 255]
  [181 181 181 255]
  ...
  [ 73  73  73 255]
  [ 73  73  73 255]
  [ 73  73  73 255]]

 ...

 [[ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]
  ...
  [235 235 235 255]
  [235 235 235 255]
  [235 235 235 255]]

 [[ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]
  ...
  [235 235 235 255]
  [235 235 235 255]
  [235 235 235 255]]

 [[ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]
  ...
  [235 235 235 255]
  [235 235 235 255]
  [235 235 235 255]]]
